// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TimebookSummary {
    /**
     * Map of task short to total duration in minutes
     */
    "Entries": { [_: string]: number };

    /**
     * Total duration in minutes
     */
    "TotalMins": number;

    /** Creates a new TimebookSummary instance. */
    constructor($$source: Partial<TimebookSummary> = {}) {
        if (!("Entries" in $$source)) {
            this["Entries"] = {};
        }
        if (!("TotalMins" in $$source)) {
            this["TotalMins"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimebookSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TimebookSummary {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Entries" in $$parsedSource) {
            $$parsedSource["Entries"] = $$createField0_0($$parsedSource["Entries"]);
        }
        return new TimebookSummary($$parsedSource as Partial<TimebookSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
