// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function AddWork(): $CancellablePromise<void> {
    return $Call.ByID(3026330686);
}

export function AddWorkBreak(): $CancellablePromise<void> {
    return $Call.ByID(1111983797);
}

export function AddWorkEnd(): $CancellablePromise<void> {
    return $Call.ByID(3107354427);
}

/**
 * Try to load a timebook file.
 * 
 * Tries to load a file named {filename}.json, which should be located
 * in current data folder.
 * 
 * If no file with expected name is found, or if loading the file fails,
 * the newly cached data is empty.
 * 
 * If current cached data is not empty when loading a new one, it is
 * saved before loading the new data.
 */
export function LoadFile(filename: string): $CancellablePromise<void> {
    return $Call.ByID(297432170, filename);
}

/**
 * Try to save a timebook file.
 * 
 * This will save existing cached data to a file named {p.filename}.json
 * to data/ folder. If the file already exists it will be overwritten.
 * 
 * If filename is empty or there is no cached data, nothing will happen.
 */
export function SaveFile(): $CancellablePromise<void> {
    return $Call.ByID(3624329819);
}
