// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function LoadFile(filePath: string): $CancellablePromise<$models.TimebookSummary> {
    return $Call.ByID(1022382219, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(1570251951);
}

// Private type creation functions
const $$createType0 = $models.TimebookSummary.createFrom;
